services:
  - type: web
    name: english-talking-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn english_bot:app --host 0.0.0.0 --port 10000
    envVars:
      - key: TELEGRAM_TOKEN
        value: 7987349101:AAGJOTrPonSWr1yNBsG_TT9IUt2BAUekQ80
    plan: Professional
